package logma

var (
	dynoErrorSentinel   = []byte("Error R")
	dynoLoadMsgSentinel = []byte("sample#load_avg_1m")
	dynoMemMsgSentinel  = []byte("sample#memory_total")
	routerSentinel      = []byte("router")
	tokenPrefix         = []byte("t.")
	keyAt               = []byte("at")
	keyBytes            = []byte("bytes")
	keyCode             = []byte("code")
	keyCodeBlank        = []byte(" code=blank-app")
	keyCodeH            = []byte(" code=H")
	keyConnect          = []byte("connect")
	keyDesc             = []byte("desc")
	keyDescBlank        = []byte(" desc=\"Blank app\"")
	keyDyno             = []byte("dyno")
	keyFwd              = []byte("fwd")
	keyHost             = []byte("host")
	keyLoadAvg15Min     = []byte("load_avg_15m")
	keyLoadAvg1Min      = []byte("load_avg_1m")
	keyLoadAvg5Min      = []byte("load_avg_5m")
	keyMemoryCache      = []byte("memory_cache")
	keyMemoryPgpgin     = []byte("memory_pgpgin")
	keyMemoryPgpgout    = []byte("memory_pgpgout")
	keyMemoryRSS        = []byte("memory_rss")
	keyMemorySwap       = []byte("memory_swap")
	keyMemoryTotal      = []byte("memory_total")
	keyMethod           = []byte("method")
	keyPath             = []byte("path")
	keyRequestID        = []byte("request_id")
	keyService          = []byte("service")
	keySock             = []byte("sock")
	keySource           = []byte("source")
	keyStatus           = []byte("status")
)
